### ISSUE TITLE
Breaks when trying to show dual displays.

### ISSUE THREAD

**Issue by nullnullnull999** [FrenzyExists/frenzch.sh#8]
I currently have a dual monitor setup and the display section glitches out trying to show both my 1920x1080 monitors.

![image](https://user-images.githubusercontent.com/85619855/131238472-91528696-b644-432c-8135-c8b2bd028ddf.png)
![image](https://user-images.githubusercontent.com/85619855/131238480-101ed5aa-bbc2-450b-8d96-90d267d30501.png)

What it should probably do (ft. neofetch)
![image](https://user-images.githubusercontent.com/85619855/131238497-6d67e163-bc09-4467-9869-2d7b46c2deab.png)

**Comment by FrenzyExists** [comment]
Ah I see, mmm, I think the prob is with the extra spacing, the resolution is obtained by 
`xrandr --current | grep ' connected' | grep -o '[0-9]\+x[0-9]\+'`
and to keep the size consistent:
`size=$((32 - $(echo "$res" | wc -m) - $(echo "display" | wc -m) - 2))`
Since having the res called twice is quite a large string because the fetch size is 32 letters (hardcoded atm), I think I could add something like
`display ........ 1920x1080 (2)`
as a way to show there's two monitors of the same size, I still wonder how I could keep the sizing if both monitors are of different sizes :thinking: . I'll keep in it mind, I'll let you know if I fix the issue, thanks for the heads up! :+1:

**Comment by FrenzyExists** [comment]
Update:

@glintty I finally fixed the issue, two years late but heyyy better late than never.
